app_evenement:
    resource: "@AppBundle/Controller/EvenementController.php"
    type:     annotation

app_promotion:
    resource: "@AppBundle/Controller/PromotionController.php"
    type:     annotation

app_user:
    resource: "@AppBundle/Controller/UserController.php"
    type:     annotation

app_module:
    resource: "@AppBundle/Controller/ModuleController.php"
    type:     annotation

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
app:
    resource: '@AppBundle/Controller/'
    type: annotation

# app/config/routing.yml
#
#fos_message:
#    resource: "@FOSMessageBundle/Resources/config/routing.xml"
#    prefix: /optional_routing_prefix

